In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pymcel as pc

Bienvenido a PyMCel v0.9.10 ¡al infinito y más allá!


Date: Feb 26 - 2026

In [2]:
tabla_sol, jd_sol, pos_vel_sol = pc.consulta_horizons(id = "sun", location = "@0", epochs = "2026-02-26")
tabla_jupiter, jd_jupiter, pos_vel_jupiter = pc.consulta_horizons(id = "jupiter barycenter", location = "@0", epochs = "2026-02-26")

In [3]:
# Generated by Copilot on "2026-02-26"!!
# Extract the state vectors returned by pymcel/Horizons
# - `tabla_*` keeps the original Horizons units (often AU and AU/day).
# - `pos_vel_*` is converted by pymcel to SI by default: meters and meters/second.
# Convention: state = [x, y, z, vx, vy, vz] (barycentric because location='@0')

state_sol_0_si = np.array(pos_vel_sol).reshape(-1, 6)[0]
state_jupiter_0_si = np.array(pos_vel_jupiter).reshape(-1, 6)[0]

r_sol_0_m = state_sol_0_si[:3]
v_sol_0_mps = state_sol_0_si[3:]
r_jupiter_0_m = state_jupiter_0_si[:3]
v_jupiter_0_mps = state_jupiter_0_si[3:]

# Aliases without unit suffix (values remain SI)
r_sol_0 = r_sol_0_m
v_sol_0 = v_sol_0_mps
r_jupiter_0 = r_jupiter_0_m
v_jupiter_0 = v_jupiter_0_mps

In [4]:
# Generated by Copilot on "2026-02-26"!!
deltat_s = 1 * 86400  # 1 day in seconds
r_jupiter_dt_m = r_jupiter_0_m + v_jupiter_0_mps * deltat_s
r_sol_dt_m = r_sol_0_m + v_sol_0_mps * deltat_s
r_jupiter_0_m, r_jupiter_dt_m

(array([-3.13499559e+11,  7.16531655e+11,  4.04379637e+09]),
 array([-3.14547192e+11,  7.16132604e+11,  4.06889651e+09]))

In [5]:
# Generated by Copilot on "2026-02-26"!!
# Gravitational parameters in SI [m^3/s^2] from pymcel.constantes
mu_sol = pc.constantes.mu_sun
mu_jupiter = pc.constantes.mu_jupiter

# Relative position vector [m]
r_ij_vec_m = r_jupiter_0_m - r_sol_0_m

mu_sol, mu_jupiter, r_ij_vec_m

(1.3271244004127942e+20,
 1.267127641e+17,
 array([-3.13100292e+11,  7.17355745e+11,  4.02525337e+09]))

In [7]:
rij_vec_sol = r_sol_0_m - r_jupiter_0_m
v_sol_dt = v_sol_0_mps - mu_jupiter * rij_vec_sol / np.linalg.norm(rij_vec_sol)**3 * deltat_s
v_sol_dt

array([12.2036746 ,  1.25570472, -0.24251222])